package com;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author donaldmears
 */
public class JCarlysCatering extends javax.swing.JFrame {

    /**
     * Creates new form JCarlysCatering
     *
     */
    int total;
    int guest;
    int entree;
    int side1 = -1;
    int side2 = -1;
    int dessert;
    int entreeCount = 1;
    int sideCount = 1;
    double totalPerGuest = 35;
    private final String[] entrees = {"Salmon", "Steak", "Chicken", "Pork"};
    private final String[] sides = {"Mashed Potatos", "Broccoli", "Mac & Cheese", "Cauliflower"};
    private final String[] desserts = {"Ice Cream", "Cheesecake", "Cookies"};

    public JCarlysCatering() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entree1 = new javax.swing.JButton();
        entree2 = new javax.swing.JButton();
        entree3 = new javax.swing.JButton();
        entree4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        side1b1 = new javax.swing.JButton();
        side1b2 = new javax.swing.JButton();
        side1b3 = new javax.swing.JButton();
        side1b4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        side2b2 = new javax.swing.JButton();
        side2b1 = new javax.swing.JButton();
        side2b4 = new javax.swing.JButton();
        side2b3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        side2b5 = new javax.swing.JButton();
        side2b6 = new javax.swing.JButton();
        dessertb1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        entreeTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sideTextField1 = new javax.swing.JTextField();
        sideTextField2 = new javax.swing.JTextField();
        dessertTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Carlys Catering");

        jLabel2.setText("Enter Guest No.");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose Entree");

        entree1.setText("Salmon");
        entree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree1ActionPerformed(evt);
            }
        });

        entree2.setText("Steak");
        entree2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree2ActionPerformed(evt);
            }
        });

        entree3.setText("Chicken");
        entree3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree3ActionPerformed(evt);
            }
        });

        entree4.setText("Pork");
        entree4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Choose Side 1");

        side1b1.setText("Mashed Pot.");
        side1b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side1b1ActionPerformed(evt);
            }
        });

        side1b2.setText("Broccoli");
        side1b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side1b2ActionPerformed(evt);
            }
        });

        side1b3.setText("Mac & Cheese");
        side1b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side1b3ActionPerformed(evt);
            }
        });

        side1b4.setText("Cauliflower");
        side1b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side1b4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Choose Side 2");

        side2b2.setText("Broccoli");
        side2b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side2b2ActionPerformed(evt);
            }
        });

        side2b1.setText("Mashed Pot.");
        side2b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side2b1ActionPerformed(evt);
            }
        });

        side2b4.setText("Cauliflower");
        side2b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side2b4ActionPerformed(evt);
            }
        });

        side2b3.setText("Mac & Cheese");
        side2b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side2b3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Choose Dessert");

        side2b5.setText("Cookies");
        side2b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side2b5ActionPerformed(evt);
            }
        });

        side2b6.setText("Cheesecake");
        side2b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side2b6ActionPerformed(evt);
            }
        });

        dessertb1.setText("Ice Cream");
        dessertb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessertb1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Order Summary");

        jLabel8.setText("Price");

        priceTextField.setEditable(false);
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        entreeTextField.setEditable(false);
        entreeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreeTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Entree");

        sideTextField1.setEditable(false);
        sideTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideTextField1ActionPerformed(evt);
            }
        });

        sideTextField2.setEditable(false);
        sideTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideTextField2ActionPerformed(evt);
            }
        });

        dessertTextField.setEditable(false);
        dessertTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessertTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Side 1");

        jLabel11.setText("Side 2");

        jLabel12.setText("Dessert");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entree3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(entree1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(side1b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(side1b3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(entree2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(entree4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(side1b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(side1b4, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(side2b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(side2b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(side2b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(side2b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(dessertb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(side2b6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(side2b5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10))
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entreeTextField)
                            .addComponent(priceTextField)
                            .addComponent(sideTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(sideTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(dessertTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entree1)
                    .addComponent(entree2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entree3)
                    .addComponent(entree4))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(side1b1)
                    .addComponent(side1b2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(side1b3)
                    .addComponent(side1b4))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(side2b2)
                    .addComponent(side2b1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(side2b4)
                    .addComponent(side2b3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(side2b5)
                    .addComponent(side2b6)
                    .addComponent(dessertb1))
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sideTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sideTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dessertTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        try {
            guest = Integer.parseInt(jTextField1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Not a numeric response, guest set to 0");
            guest = 0;
        }
        double total = guest * totalPerGuest;
        priceTextField.setText(total + " ");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void entree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree1ActionPerformed

        entree = 0;
        entreeTextField.setText(entrees[entree]);
    }//GEN-LAST:event_entree1ActionPerformed

    private void entree2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree2ActionPerformed
      
        entree = 1;
        entreeTextField.setText(entrees[entree]);
    }//GEN-LAST:event_entree2ActionPerformed

    private void entree3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree3ActionPerformed
       
        entree = 2;
        entreeTextField.setText(entrees[entree]);
    }//GEN-LAST:event_entree3ActionPerformed

    private void entree4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree4ActionPerformed
        
        entree = 3;
        entreeTextField.setText(entrees[entree]);
    }//GEN-LAST:event_entree4ActionPerformed

    private void side1b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side1b1ActionPerformed
        side1 = 0;
        sideTextField1.setText(sides[side1]);
        if (side2 > -1) {
            sideCount++;
        }
        if (sideCount > 2) {
            JOptionPane.showMessageDialog(rootPane, "Can only choose two sides, choose again.");
            side1 = -1;
            side2 = -1;
            sideCount = 1;
            sideTextField1.setText(" ");
            sideTextField2.setText(" ");
        }
    }//GEN-LAST:event_side1b1ActionPerformed

    private void side1b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side1b2ActionPerformed
        side1 = 1;
        sideTextField1.setText(sides[side1]);
        if (side2 > -1) {
            sideCount++;
        }
        if (sideCount > 2) {
            JOptionPane.showMessageDialog(rootPane, "Can only choose two sides, choose again.");
            side1 = -1;
            side2 = -1;
            sideCount = 1;
            sideTextField1.setText(" ");
            sideTextField2.setText(" ");
        }
    }//GEN-LAST:event_side1b2ActionPerformed

    private void side1b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side1b3ActionPerformed
        side1 = 2;
        sideTextField1.setText(sides[side1]);
        if (side2 > -1) {
            sideCount++;
        }
        if (sideCount > 2) {
            JOptionPane.showMessageDialog(rootPane, "Can only choose two sides, choose again.");
            side1 = -1;
            side2 = -1;
            sideCount = 1;
            sideTextField1.setText(" ");
            sideTextField2.setText(" ");
        }
    }//GEN-LAST:event_side1b3ActionPerformed

    private void side1b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side1b4ActionPerformed
        side1 = 3;
        sideTextField1.setText(sides[side1]);
        if (side2 > -1) {
            sideCount++;
        }
        if (sideCount > 2) {
            JOptionPane.showMessageDialog(rootPane, "Can only choose two sides, choose again.");
            side1 = -1;
            side2 = -1;
            sideCount = 1;
            sideTextField1.setText(" ");
            sideTextField2.setText(" ");
        }
    }//GEN-LAST:event_side1b4ActionPerformed

    private void side2b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side2b2ActionPerformed
        side2 = 0;
        sideTextField2.setText(sides[side2]);
        if (side1 > -1) {
            sideCount++;
        }
        if (sideCount > 2) {
            JOptionPane.showMessageDialog(rootPane, "Can only choose two sides, choose again.");
            side1 = -1;
            side2 = -1;
            sideCount = 1;
            sideTextField1.setText(" ");
            sideTextField2.setText(" ");
        }
    }//GEN-LAST:event_side2b2ActionPerformed

    private void side2b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side2b1ActionPerformed
        side2 = 1;
        sideTextField2.setText(sides[side2]);
        if (side1 > -1) {
            sideCount++;
        }
        if (sideCount > 2) {
            JOptionPane.showMessageDialog(rootPane, "Can only choose two sides, choose again.");
            side1 = -1;
            side2 = -1;
            sideCount = 1;
            sideTextField1.setText(" ");
            sideTextField2.setText(" ");
        }
    }//GEN-LAST:event_side2b1ActionPerformed

    private void side2b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side2b4ActionPerformed
        side2 = 2;
        sideTextField2.setText(sides[side2]);
        if (side1 > -1) {
            sideCount++;
        }
        if (sideCount > 2) {
            JOptionPane.showMessageDialog(rootPane, "Can only choose two sides, choose again.");
            side1 = -1;
            side2 = -1;
            sideCount = 1;
            sideTextField1.setText(" ");
            sideTextField2.setText(" ");
        }
    }//GEN-LAST:event_side2b4ActionPerformed

    private void side2b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side2b3ActionPerformed
        side2 = 3;
        sideTextField2.setText(sides[side2]);
        if (side1 > -1) {
            sideCount++;
        }
        if (sideCount > 2) {
            JOptionPane.showMessageDialog(rootPane, "Can only choose two sides, choose again.");
            side1 = -1;
            side2 = -1;
            sideCount = 1;
            sideTextField1.setText(" ");
            sideTextField2.setText(" ");
        }
    }//GEN-LAST:event_side2b3ActionPerformed

    private void side2b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side2b5ActionPerformed
        dessert = 0;
        dessertTextField.setText(desserts[dessert]);
    }//GEN-LAST:event_side2b5ActionPerformed

    private void side2b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side2b6ActionPerformed
        dessert = 1;
        dessertTextField.setText(desserts[dessert]);
    }//GEN-LAST:event_side2b6ActionPerformed

    private void dessertb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessertb1ActionPerformed
        dessert = 2;
        dessertTextField.setText(desserts[dessert]);
    }//GEN-LAST:event_dessertb1ActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed

    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void entreeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreeTextFieldActionPerformed
        
    }//GEN-LAST:event_entreeTextFieldActionPerformed

    private void sideTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sideTextField1ActionPerformed

    private void sideTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sideTextField2ActionPerformed

    private void dessertTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessertTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dessertTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCarlysCatering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCarlysCatering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCarlysCatering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCarlysCatering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCarlysCatering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dessertTextField;
    private javax.swing.JButton dessertb1;
    private javax.swing.JButton entree1;
    private javax.swing.JButton entree2;
    private javax.swing.JButton entree3;
    private javax.swing.JButton entree4;
    private javax.swing.JTextField entreeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton side1b1;
    private javax.swing.JButton side1b2;
    private javax.swing.JButton side1b3;
    private javax.swing.JButton side1b4;
    private javax.swing.JButton side2b1;
    private javax.swing.JButton side2b2;
    private javax.swing.JButton side2b3;
    private javax.swing.JButton side2b4;
    private javax.swing.JButton side2b5;
    private javax.swing.JButton side2b6;
    private javax.swing.JTextField sideTextField1;
    private javax.swing.JTextField sideTextField2;
    // End of variables declaration//GEN-END:variables
}
